import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const azeretMono = localFont({
  src: "./fonts/AzeretMono-Variable.woff2",
  variable: "--font-azeret-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={azeretMono.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
